name: test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.7.1'
    - run: dotnet --version
